import { queryClient } from '@/lib/queryClient'
import { QueryClientProvider } from '@tanstack/react-query'
import type { Metadata } from 'next'
import { Navbar } from './_ui/Navbar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <QueryClientProvider client={queryClient}>
          <Navbar />
          <main className="container mx-auto p-6">{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  )
}
